FROM ghcr.io/banesullivan/localtileserver-jupyter:0.4.3

COPY . ${HOME}
WORKDIR ${HOME}

ARG LOCALTILESERVER_CLIENT_PREFIX='proxy/{port}'
ENV LOCALTILESERVER_CLIENT_PREFIX=$LOCALTILESERVER_CLIENT_PREFIX
